name: Release Chinese Kenan Modpack

on:
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  deploy:
    environment: Translation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15'

      - name: Install Dependency
        run: npm install

      - name: 拉取 Kenan 最新内容 by Merge from Upstream Repository
        continue-on-error: true
        # rebase 太慢了
        uses: dabreadman/sync-upstream-repo@v1.0.0.b
        env:
          # Required, URL to upstream (fork base)
          UPSTREAM_URL: "https://github.com/Kenan2000/CDDA-Kenan-Modpack.git"
          # Optional merge arguments
          MERGE_ARGS: ""
          # Optional push arguments
          PUSH_ARGS: ""
        with:
          upstream_repo: ${{ env.UPSTREAM_URL }}
          upstream_branch: master
          downstream_branch: master
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 拉取 Paratranz 最新内容
        run: npm run import-paratranz
        env:
          PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}
      - name: Build Mod
        run: npm start
        env:
          BAIDU_TRANSLATION_APP_ID: ${{ secrets.BAIDU_TRANSLATION_APP_ID }}
          BAIDU_TRANSLATION_SECRET: ${{ secrets.BAIDU_TRANSLATION_SECRET }}
          SOUGOU_TRANSLATION_APP_ID: ${{ secrets.SOUGOU_TRANSLATION_APP_ID }}
          SOUGOU_TRANSLATION_SECRET: ${{ secrets.SOUGOU_TRANSLATION_SECRET }}
      - name: Build Wiki
        run: npm run build-wiki

      - uses: montudor/action-zip@v0.1.1
        with:
          args: zip -qq -r Kenan-Modpack-Mod汉化版.zip Kenan-Modpack-Chinese/

      - name: Release Mod
        uses: marvinpinto/action-automatic-releases@v1.1.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: 'latest'
          prerelease: false
          title: '最新CDDA-Kenan-Mod合集汉化版'
          files: |
            Kenan-Modpack-Mod汉化版.zip
      - name: Deploy Tiddlywiki
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public-dist
          
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.2.0
        with:
          message: 'feat: 自动拉取Paratranz最新内容并发布'
          pull_strategy: NO-PULL
